#!/bin/bash
# Quick setup script for pushing to GitHub and deploying to Replit

echo "=================================================="
echo "  LangGraph Chatbot → GitHub → Replit Deploy"
echo "=================================================="
echo ""
echo "✓ Bước 1: Git repo đã khởi tạo & commit"
echo "✓ Bước 2: Files đã staged"
echo ""
echo "⏭️  Tiếp theo: Push lên GitHub"
echo ""
echo "📝 HƯỚNG DẪN CHI TIẾT:"
echo ""
echo "1️⃣  Tạo Repository trên GitHub:"
echo "   → Truy cập: https://github.com/new"
echo "   → Repository name: chatbot-langgraph"
echo "   → Chọn Public hoặc Private"
echo "   → Bỏ chọn 'Add a README.md'"
echo "   → Click 'Create repository'"
echo ""
echo "2️⃣  Copy lệnh push từ GitHub, ví dụ:"
echo "   git remote add origin https://github.com/YOUR-USERNAME/chatbot-langgraph.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "   (Thay YOUR-USERNAME bằng username GitHub của bạn)"
echo ""
echo "3️⃣  Chạy lệnh trên terminal này"
echo ""
echo "4️⃣  Sau khi push xong, truy cập Replit:"
echo "   → https://replit.com/~"
echo "   → Click '+ Create' → 'Import from GitHub'"
echo "   → Dán GitHub URL: https://github.com/YOUR-USERNAME/chatbot-langgraph"
echo ""
echo "5️⃣  Cấu hình Secrets trên Replit (🔐):"
echo "   → GROQ_API_KEY: <GROQ_API_KEY>"
echo "   → TAVILY_API_KEY: <TAVILY_API_KEY>"
echo ""
echo "6️⃣  Click 'Run' để khởi chạy ứng dụng trên Replit"
echo ""
echo "=================================================="
echo ""
echo "📌 Lưu ý:"
echo "   • .env chứa API keys → KHÔNG commit vào Git"
echo "   • Sử dụng Replit Secrets để lưu trữ keys"
echo "   • chat_history/ được generate tự động"
echo ""
